--delete from entities_tab;
insert into entities_tab (identity_type, identity, currency, amount) values ('Supplier', 'Supp Dude', 'EUR', 1012.69);
insert into entities_tab (identity_type, identity, currency, amount) values ('Supplier', 'George Doors', 'GBP', 1200);
insert into entities_tab (identity_type, identity, currency, amount) values ('Customer', 'Car Bits', 'GBP', 600.78);
insert into entities_tab (identity_type, identity, currency, amount) values ('Supplier', 'Green Engines', 'GBP', 354);
insert into entities_tab (identity_type, identity, currency, amount) values ('Customer', 'Ford', 'SEK', 789.54);
insert into entities_tab (identity_type, identity, currency, amount) values ('Customer', 'Ford', 'GBP', 416.8);
insert into entities_tab (identity_type, identity, currency, amount) values ('Customer', 'Volvo', 'GBP', 168.56);
insert into entities_tab (identity_type, identity, currency, amount) values ('Customer', 'Ford', 'USD', 56.4);
insert into entities_tab (identity_type, identity, currency, amount) values ('Customer', 'Car Bits', 'EUR', 333.34);
insert into entities_tab (identity_type, identity, currency, amount) values ('Supplier', 'George Doors', 'EUR', 56.4);
commit;
