[Item1]
Description=runExcelTest-01-Base01-CellFormatting
TestScript=01-basicTests\runExcelTest-01-Base01-CellFormatting.tst
NewSession=False
Enabled=True
Performance=
Var1Name=output_file
Var1Enabled=True
Var1Global=True
Var1Type=String
Var1InputValue=no
Var1OutputValue=
[Item2]
Description=runExcelTest-01-Base02-Date1900-v1
TestScript=01-basicTests\runExcelTest-01-Base02-Date1900-v1.tst
NewSession=False
Enabled=True
Performance=
Var1Name=output_file
Var1Enabled=True
Var1Global=True
Var1Type=String
Var1InputValue=
Var1OutputValue=
[Item3]
Description=runExcelTest-01-Base02-Date1900-v2
TestScript=01-basicTests\runExcelTest-01-Base02-Date1900-v2.tst
NewSession=False
Enabled=True
Performance=
Var1Name=output_file
Var1Enabled=True
Var1Global=True
Var1Type=String
Var1InputValue=
Var1OutputValue=
[Item4]
Description=runExcelTest-01-Base03-ImageHypCommentDefnm
TestScript=01-basicTests\runExcelTest-01-Base03-ImageHypCommentDefnm.tst
NewSession=False
Enabled=True
Performance=
Var1Name=output_file
Var1Enabled=True
Var1Global=True
Var1Type=String
Var1InputValue=
Var1OutputValue=
[Item5]
Description=runExcelTest-02-Tables01-SimpleiTable
TestScript=02-tableTests\runExcelTest-02-Tables01-SimpleiTable.tst
NewSession=False
Enabled=True
Performance=
Var1Name=output_file
Var1Enabled=True
Var1Global=True
Var1Type=String
Var1InputValue=
Var1OutputValue=
[Item6]
Description=runExcelTest-02-Tables02-MultiTablesOnPage
TestScript=02-tableTests\runExcelTest-02-Tables02-MultiTablesOnPage.tst
NewSession=False
Enabled=True
Performance=
Var1Name=output_file
Var1Enabled=True
Var1Global=True
Var1Type=String
Var1InputValue=
Var1OutputValue=
[Item7]
Description=runExcelTest-02-Tables03-TablesWithOtherRels
TestScript=02-tableTests\runExcelTest-02-Tables03-TablesWithOtherRels.tst
NewSession=False
Enabled=True
Performance=
Var1Name=output_file
Var1Enabled=True
Var1Global=True
Var1Type=String
Var1InputValue=
Var1OutputValue=
[Item8]
Description=runExcelTest-02-Tables04-q2sNoTableWithTitles
TestScript=02-tableTests\runExcelTest-02-Tables04-q2sNoTableWithTitles.tst
NewSession=False
Enabled=True
Performance=
Var1Name=output_file
Var1Enabled=True
Var1Global=True
Var1Type=String
Var1InputValue=
Var1OutputValue=
[Item9]
Description=runExcelTest-02-Tables05-q2tMultiplesTesting
TestScript=02-tableTests\runExcelTest-02-Tables05-q2tMultiplesTesting.tst
NewSession=False
Enabled=True
Performance=
Var1Name=output_file
Var1Enabled=True
Var1Global=True
Var1Type=String
Var1InputValue=
Var1OutputValue=

[Notes]
{\rtf1\ansi\ansicpg1252\deff0\deflang2057{\fonttbl{\f0\fnil\fcharset0 Arial;}}
\viewkind4\uc1\pard\fs20\par
}
